version: '3.5'

services:
  server:
    image: nginx
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    container_name: nginx

networks:
  default:
    external: true
    name: network
